import { Company, Job } from './types';

export const SEED_COMPANIES: Company[] = [
  {
    id: 'c1',
    name: 'TechVision Solutions',
    logo: 'TV',
    industry: 'Technology',
    location: 'Karachi',
    website: 'https://techvision.example.com',
    description:
      'TechVision Solutions builds cloud-native software products for enterprises across South Asia, specializing in AI-driven analytics and developer tooling.',
    size: '201-500',
  },
  {
    id: 'c2',
    name: 'Nova Digital Agency',
    logo: 'ND',
    industry: 'Marketing',
    location: 'Lahore',
    website: 'https://novadigital.example.com',
    description:
      'Nova Digital Agency is a full-service digital marketing firm helping brands grow through performance marketing, SEO, and creative content.',
    size: '51-200',
  },
  {
    id: 'c3',
    name: 'GreenLeaf Finance',
    logo: 'GL',
    industry: 'Finance',
    location: 'Islamabad',
    website: 'https://greenleaf.example.com',
    description:
      'GreenLeaf Finance provides modern banking and microfinance solutions with a mission to expand financial inclusion across the region.',
    size: '501-1000',
  },
  {
    id: 'c4',
    name: 'BrightPath Education',
    logo: 'BP',
    industry: 'Education',
    location: 'Remote',
    website: 'https://brightpath.example.com',
    description:
      'BrightPath Education delivers online courses and tutoring services to thousands of students, from K-12 to professional certifications.',
    size: '51-200',
  },
  {
    id: 'c5',
    name: 'MediCare Plus',
    logo: 'MP',
    industry: 'Healthcare',
    location: 'Faisalabad',
    website: 'https://medicareplus.example.com',
    description:
      'MediCare Plus operates a network of clinics and pharmacies providing affordable healthcare and telemedicine services.',
    size: '201-500',
  },
  {
    id: 'c6',
    name: 'Skyline Sales Co.',
    logo: 'SK',
    industry: 'Sales',
    location: 'Multan',
    website: 'https://skyline.example.com',
    description:
      'Skyline Sales Co. is a fast-growing sales and distribution company representing major consumer brands nationwide.',
    size: '51-200',
  },
  {
    id: 'c7',
    name: 'PixelCraft Studio',
    logo: 'PC',
    industry: 'Creative',
    location: 'Remote',
    website: 'https://pixelcraft.example.com',
    description:
      'PixelCraft Studio is a boutique creative agency crafting brand identities, motion graphics, and product design for startups.',
    size: '11-50',
  },
  {
    id: 'c8',
    name: 'CloudOps Systems',
    logo: 'CO',
    industry: 'Technology',
    location: 'Islamabad',
    website: 'https://cloudops.example.com',
    description:
      'CloudOps Systems offers DevOps and infrastructure automation consulting, helping teams ship faster and scale reliably.',
    size: '51-200',
  },
  {
    id: 'c9',
    name: 'Horizon Retail',
    logo: 'HR',
    industry: 'Customer Service',
    location: 'Hyderabad',
    website: 'https://horizon.example.com',
    description:
      'Horizon Retail runs a chain of department stores with a strong customer support and service backbone.',
    size: '201-500',
  },
  {
    id: 'c10',
    name: 'DataForge Labs',
    logo: 'DF',
    industry: 'Technology',
    location: 'Lahore',
    website: 'https://dataforge.example.com',
    description:
      'DataForge Labs builds data platforms and ML pipelines for fintech and retail, with a focus on actionable analytics.',
    size: '11-50',
  },
];

const now = new Date();
const daysAgo = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d.toISOString();
};
const daysAhead = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + n);
  return d.toISOString();
};

export const SEED_JOBS: Job[] = [
  {
    id: 'j1',
    title: 'Senior Frontend Developer',
    companyId: 'c1',
    category: 'technology',
    subcategory: 'Frontend Developer',
    location: 'Karachi',
    jobType: 'Full Time',
    workMode: 'Hybrid',
    salaryMin: 180000,
    salaryMax: 280000,
    currency: 'PKR',
    experienceYears: 4,
    education: 'Bachelor',
    skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'REST APIs'],
    description:
      'We are looking for a Senior Frontend Developer to lead the development of our customer-facing dashboards. You will work closely with product and backend teams to deliver polished, accessible interfaces.',
    responsibilities:
      'Architect and build scalable frontend features.\nMentor junior developers and review code.\nCollaborate with designers to implement pixel-perfect UIs.\nOptimize performance and accessibility.',
    requirements:
      '4+ years of frontend experience.\nStrong React and TypeScript skills.\nExperience with state management and testing.\nGood understanding of web performance.',
    benefits: 'Health insurance, annual bonus, remote-friendly, learning budget.',
    postedDate: daysAgo(2),
    deadline: daysAhead(18),
    featured: true,
    status: 'Active',
    rating: 4.5,
    applicantsCount: 12,
  },
  {
    id: 'j2',
    title: 'Junior Python Developer',
    companyId: 'c10',
    category: 'technology',
    subcategory: 'Python Developer',
    location: 'Lahore',
    jobType: 'Full Time',
    workMode: 'On Site',
    salaryMin: 80000,
    salaryMax: 130000,
    currency: 'PKR',
    experienceYears: 1,
    education: 'Bachelor',
    skills: ['Python', 'Django', 'PostgreSQL', 'Git'],
    description:
      'Join our backend team as a Junior Python Developer. You will help build and maintain APIs and data pipelines powering our analytics products.',
    responsibilities:
      'Develop and maintain Django REST APIs.\nWrite clean, tested code.\nCollaborate with senior engineers on architecture.',
    requirements:
      'Basic Python and Django knowledge.\nUnderstanding of relational databases.\nWillingness to learn and grow.',
    benefits: 'Mentorship program, health insurance, flexible hours.',
    postedDate: daysAgo(5),
    deadline: daysAhead(12),
    featured: false,
    status: 'Active',
    rating: 4.0,
    applicantsCount: 28,
  },
  {
    id: 'j3',
    title: 'Python Intern',
    companyId: 'c10',
    category: 'technology',
    subcategory: 'Python Developer',
    location: 'Remote',
    jobType: 'Internship',
    workMode: 'Remote',
    salaryMin: 25000,
    salaryMax: 40000,
    currency: 'PKR',
    experienceYears: 0,
    education: 'Bachelor',
    skills: ['Python', 'SQL', 'Git'],
    description:
      'A paid remote internship for students and freshers looking to start a career in Python backend development.',
    responsibilities:
      'Assist with bug fixes and small features.\nWrite unit tests.\nParticipate in code reviews.',
    requirements: 'Familiarity with Python basics.\nEagerness to learn.\nGood communication.',
    benefits: 'Stipend, mentorship, certificate on completion.',
    postedDate: daysAgo(7),
    deadline: daysAhead(10),
    featured: true,
    status: 'Active',
    rating: 4.2,
    applicantsCount: 45,
  },
  {
    id: 'j4',
    title: 'Digital Marketing Specialist',
    companyId: 'c2',
    category: 'marketing',
    subcategory: 'Digital Marketing',
    location: 'Lahore',
    jobType: 'Full Time',
    workMode: 'Hybrid',
    salaryMin: 90000,
    salaryMax: 160000,
    currency: 'PKR',
    experienceYears: 2,
    education: 'Bachelor',
    skills: ['SEO', 'Google Ads', 'Meta Ads', 'Analytics'],
    description:
      'Drive paid and organic marketing campaigns for our clients across multiple channels and report on performance.',
    responsibilities:
      'Plan and execute ad campaigns.\nOptimize landing pages for conversions.\nPrepare performance reports.',
    requirements: '2+ years in digital marketing.\nExperience with Google and Meta ad platforms.\nAnalytical mindset.',
    benefits: 'Performance bonuses, internet allowance, training budget.',
    postedDate: daysAgo(3),
    deadline: daysAhead(20),
    featured: false,
    status: 'Active',
    rating: 4.1,
    applicantsCount: 19,
  },
  {
    id: 'j5',
    title: 'Social Media Intern',
    companyId: 'c2',
    category: 'marketing',
    subcategory: 'Social Media Manager',
    location: 'Remote',
    jobType: 'Internship',
    workMode: 'Remote',
    salaryMin: 15000,
    salaryMax: 25000,
    currency: 'PKR',
    experienceYears: 0,
    education: 'Intermediate',
    skills: ['Instagram', 'Canva', 'Content Writing'],
    description: 'Support our social media team in creating engaging content for client brands.',
    responsibilities: 'Schedule posts.\nCreate graphics in Canva.\nEngage with audiences.',
    requirements: 'Creative mindset.\nFamiliarity with major social platforms.\nGood writing skills.',
    benefits: 'Stipend, flexible schedule, certificate.',
    postedDate: daysAgo(8),
    deadline: daysAhead(7),
    featured: false,
    status: 'Active',
    rating: 3.9,
    applicantsCount: 33,
  },
  {
    id: 'j6',
    title: 'Accounts Assistant',
    companyId: 'c3',
    category: 'finance',
    subcategory: 'Accounts Assistant',
    location: 'Islamabad',
    jobType: 'Full Time',
    workMode: 'On Site',
    salaryMin: 60000,
    salaryMax: 100000,
    currency: 'PKR',
    experienceYears: 1,
    education: 'Bachelor',
    skills: ['Excel', 'QuickBooks', 'Bookkeeping'],
    description: 'Assist the finance team with day-to-day accounting operations and reporting.',
    responsibilities: 'Maintain ledgers.\nPrepare invoices.\nReconcile bank statements.',
    requirements: 'Basic accounting knowledge.\nProficiency in Excel.\nAttention to detail.',
    benefits: 'Health insurance, provident fund, annual increment.',
    postedDate: daysAgo(4),
    deadline: daysAhead(14),
    featured: false,
    status: 'Active',
    rating: 3.8,
    applicantsCount: 21,
  },
  {
    id: 'j7',
    title: 'Online Math Tutor',
    companyId: 'c4',
    category: 'education',
    subcategory: 'Online Teacher',
    location: 'Remote',
    jobType: 'Part Time',
    workMode: 'Remote',
    salaryMin: 35000,
    salaryMax: 60000,
    currency: 'PKR',
    experienceYears: 1,
    education: 'Bachelor',
    skills: ['Mathematics', 'Communication', 'Online Teaching'],
    description: 'Teach mathematics to students online in one-on-one and group sessions.',
    responsibilities: 'Plan and deliver lessons.\nAssess student progress.\nProvide feedback.',
    requirements: 'Strong math fundamentals.\nReliable internet.\nTeaching experience is a plus.',
    benefits: 'Flexible hours, performance pay.',
    postedDate: daysAgo(6),
    deadline: daysAhead(25),
    featured: true,
    status: 'Active',
    rating: 4.3,
    applicantsCount: 17,
  },
  {
    id: 'j8',
    title: 'Teaching Assistant Intern',
    companyId: 'c4',
    category: 'education',
    subcategory: 'Teaching Assistant',
    location: 'Remote',
    jobType: 'Internship',
    workMode: 'Remote',
    salaryMin: 10000,
    salaryMax: 20000,
    currency: 'PKR',
    experienceYears: 0,
    education: 'Intermediate',
    skills: ['Communication', 'Organisation'],
    description: 'Assist lead teachers with grading, lesson preparation, and student support.',
    responsibilities: 'Grade assignments.\nPrepare materials.\nAnswer student queries.',
    requirements: 'Good academic record.\nPatience and communication skills.',
    benefits: 'Stipend, certificate, mentorship.',
    postedDate: daysAgo(10),
    deadline: daysAhead(5),
    featured: false,
    status: 'Active',
    rating: 4.0,
    applicantsCount: 40,
  },
  {
    id: 'j9',
    title: 'Pharmacy Technician',
    companyId: 'c5',
    category: 'healthcare',
    subcategory: 'Pharmacy',
    location: 'Faisalabad',
    jobType: 'Full Time',
    workMode: 'On Site',
    salaryMin: 70000,
    salaryMax: 110000,
    currency: 'PKR',
    experienceYears: 2,
    education: 'Diploma',
    skills: ['Pharmacy', 'Inventory Management', 'Customer Service'],
    description: 'Manage pharmacy inventory and dispense medication under pharmacist supervision.',
    responsibilities: 'Dispense medications.\nManage inventory.\nAdvise customers.',
    requirements: 'Pharmacy technician diploma.\nRelevant experience preferred.',
    benefits: 'Health insurance, staff discount.',
    postedDate: daysAgo(1),
    deadline: daysAhead(22),
    featured: false,
    status: 'Active',
    rating: 3.7,
    applicantsCount: 9,
  },
  {
    id: 'j10',
    title: 'Medical Receptionist',
    companyId: 'c5',
    category: 'healthcare',
    subcategory: 'Receptionist',
    location: 'Faisalabad',
    jobType: 'Part Time',
    workMode: 'On Site',
    salaryMin: 40000,
    salaryMax: 60000,
    currency: 'PKR',
    experienceYears: 0,
    education: 'Intermediate',
    skills: ['Communication', 'MS Office', 'Customer Service'],
    description: 'Greet patients, schedule appointments, and manage front desk operations.',
    responsibilities: 'Manage appointments.\nHandle patient inquiries.\nMaintain records.',
    requirements: 'Good communication skills.\nBasic computer literacy.\nNo experience required.',
    benefits: 'Flexible shifts, meal allowance.',
    postedDate: daysAgo(2),
    deadline: daysAhead(16),
    featured: false,
    status: 'Active',
    rating: 3.6,
    applicantsCount: 15,
  },
  {
    id: 'j11',
    title: 'Sales Executive',
    companyId: 'c6',
    category: 'sales',
    subcategory: 'Sales Executive',
    location: 'Multan',
    jobType: 'Full Time',
    workMode: 'On Site',
    salaryMin: 80000,
    salaryMax: 180000,
    currency: 'PKR',
    experienceYears: 1,
    education: 'Bachelor',
    skills: ['Sales', 'Negotiation', 'CRM'],
    description: 'Drive sales of consumer products by building relationships with retailers and distributors.',
    responsibilities: 'Meet sales targets.\nBuild distributor relationships.\nReport daily activity.',
    requirements: '1+ year in sales.\nStrong negotiation skills.\nWilling to travel.',
    benefits: 'Commission, fuel allowance, mobile allowance.',
    postedDate: daysAgo(3),
    deadline: daysAhead(19),
    featured: true,
    status: 'Active',
    rating: 4.1,
    applicantsCount: 24,
  },
  {
    id: 'j12',
    title: 'Graphic Designer',
    companyId: 'c7',
    category: 'creative',
    subcategory: 'Graphic Designer',
    location: 'Remote',
    jobType: 'Freelance',
    workMode: 'Remote',
    salaryMin: 50000,
    salaryMax: 120000,
    currency: 'PKR',
    experienceYears: 2,
    education: 'Bachelor',
    skills: ['Photoshop', 'Illustrator', 'Figma', 'Branding'],
    description: 'Create brand identities and marketing visuals for our startup clients.',
    responsibilities: 'Design logos and brand assets.\nCreate social media visuals.\nIterate with clients.',
    requirements: 'Portfolio of design work.\nProficiency in Adobe suite and Figma.',
    benefits: 'Remote work, flexible hours.',
    postedDate: daysAgo(4),
    deadline: daysAhead(13),
    featured: false,
    status: 'Active',
    rating: 4.2,
    applicantsCount: 31,
  },
  {
    id: 'j13',
    title: 'UI/UX Designer',
    companyId: 'c7',
    category: 'creative',
    subcategory: 'UI/UX Designer',
    location: 'Remote',
    jobType: 'Contract',
    workMode: 'Remote',
    salaryMin: 120000,
    salaryMax: 200000,
    currency: 'PKR',
    experienceYears: 3,
    education: 'Bachelor',
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
    description: 'Design intuitive product experiences for web and mobile applications.',
    responsibilities: 'Conduct user research.\nCreate wireframes and prototypes.\nMaintain design systems.',
    requirements: '3+ years in product design.\nStrong Figma skills.\nPortfolio required.',
    benefits: 'Remote, equipment allowance.',
    postedDate: daysAgo(6),
    deadline: daysAhead(15),
    featured: true,
    status: 'Active',
    rating: 4.4,
    applicantsCount: 26,
  },
  {
    id: 'j14',
    title: 'DevOps Engineer',
    companyId: 'c8',
    category: 'technology',
    subcategory: 'DevOps',
    location: 'Islamabad',
    jobType: 'Full Time',
    workMode: 'Hybrid',
    salaryMin: 200000,
    salaryMax: 350000,
    currency: 'PKR',
    experienceYears: 3,
    education: 'Bachelor',
    skills: ['Docker', 'Kubernetes', 'AWS', 'Terraform', 'CI/CD'],
    description: 'Build and maintain our cloud infrastructure and deployment pipelines.',
    responsibilities: 'Manage Kubernetes clusters.\nAutomate CI/CD pipelines.\nMonitor system health.',
    requirements: '3+ years in DevOps.\nStrong AWS and Kubernetes experience.\nInfrastructure as code.',
    benefits: 'Health insurance, remote-friendly, certification budget.',
    postedDate: daysAgo(1),
    deadline: daysAhead(21),
    featured: true,
    status: 'Active',
    rating: 4.5,
    applicantsCount: 14,
  },
  {
    id: 'j15',
    title: 'IT Support Intern',
    companyId: 'c8',
    category: 'technology',
    subcategory: 'IT Support',
    location: 'Islamabad',
    jobType: 'Internship',
    workMode: 'On Site',
    salaryMin: 20000,
    salaryMax: 30000,
    currency: 'PKR',
    experienceYears: 0,
    education: 'Intermediate',
    skills: ['Windows', 'Networking', 'Hardware'],
    description: 'Provide first-line IT support to employees and assist with infrastructure maintenance.',
    responsibilities: 'Resolve support tickets.\nSet up workstations.\nMaintain inventory.',
    requirements: 'Basic IT knowledge.\nProblem-solving attitude.\nNo experience required.',
    benefits: 'Stipend, hands-on training, certificate.',
    postedDate: daysAgo(9),
    deadline: daysAhead(6),
    featured: false,
    status: 'Active',
    rating: 3.8,
    applicantsCount: 38,
  },
  {
    id: 'j16',
    title: 'Customer Support Representative',
    companyId: 'c9',
    category: 'customer-service',
    subcategory: 'Customer Support',
    location: 'Hyderabad',
    jobType: 'Full Time',
    workMode: 'On Site',
    salaryMin: 55000,
    salaryMax: 90000,
    currency: 'PKR',
    experienceYears: 1,
    education: 'Intermediate',
    skills: ['Communication', 'CRM', 'Problem Solving'],
    description: 'Handle customer inquiries via phone, email, and chat and resolve issues efficiently.',
    responsibilities: 'Respond to customer queries.\nLog and track issues.\nEscalate when needed.',
    requirements: 'Good communication skills.\nCustomer-oriented attitude.\nBasic computer skills.',
    benefits: 'Health insurance, shift allowance.',
    postedDate: daysAgo(5),
    deadline: daysAhead(11),
    featured: false,
    status: 'Active',
    rating: 3.9,
    applicantsCount: 22,
  },
  {
    id: 'j17',
    title: 'Chat Support Agent',
    companyId: 'c9',
    category: 'customer-service',
    subcategory: 'Chat Support',
    location: 'Remote',
    jobType: 'Part Time',
    workMode: 'Remote',
    salaryMin: 30000,
    salaryMax: 50000,
    currency: 'PKR',
    experienceYears: 0,
    education: 'Intermediate',
    skills: ['Written Communication', 'Typing', 'CRM'],
    description: 'Provide live chat support to online customers across multiple brands.',
    responsibilities: 'Answer live chats.\nResolve customer issues.\nDocument conversations.',
    requirements: 'Fast typing speed.\nExcellent written English.\nNo experience required.',
    benefits: 'Remote, flexible shifts.',
    postedDate: daysAgo(7),
    deadline: daysAhead(9),
    featured: false,
    status: 'Active',
    rating: 3.7,
    applicantsCount: 29,
  },
  {
    id: 'j18',
    title: 'Data Analyst',
    companyId: 'c10',
    category: 'technology',
    subcategory: 'Data Analyst',
    location: 'Lahore',
    jobType: 'Full Time',
    workMode: 'Hybrid',
    salaryMin: 150000,
    salaryMax: 250000,
    currency: 'PKR',
    experienceYears: 2,
    education: 'Bachelor',
    skills: ['SQL', 'Python', 'Tableau', 'Statistics'],
    description: 'Analyze large datasets to uncover insights and build dashboards for stakeholders.',
    responsibilities: 'Build dashboards.\nRun ad-hoc analyses.\nPresent insights to teams.',
    requirements: '2+ years in analytics.\nStrong SQL and Python.\nData visualization experience.',
    benefits: 'Health insurance, learning budget.',
    postedDate: daysAgo(4),
    deadline: daysAhead(17),
    featured: true,
    status: 'Active',
    rating: 4.3,
    applicantsCount: 18,
  },
  {
    id: 'j19',
    title: 'Full Stack Developer',
    companyId: 'c1',
    category: 'technology',
    subcategory: 'Full Stack Developer',
    location: 'Karachi',
    jobType: 'Full Time',
    workMode: 'Hybrid',
    salaryMin: 200000,
    salaryMax: 320000,
    currency: 'PKR',
    experienceYears: 3,
    education: 'Bachelor',
    skills: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
    description: 'Build end-to-end features for our SaaS platform, from database to UI.',
    responsibilities: 'Design APIs.\nBuild React frontends.\nDeploy and monitor features.',
    requirements: '3+ years full stack experience.\nStrong Node.js and React skills.\nCloud experience.',
    benefits: 'Health insurance, equity, remote-friendly.',
    postedDate: daysAgo(2),
    deadline: daysAhead(23),
    featured: true,
    status: 'Active',
    rating: 4.6,
    applicantsCount: 16,
  },
  {
    id: 'j20',
    title: 'Business Analyst Intern',
    companyId: 'c3',
    category: 'business',
    subcategory: 'Business Analyst',
    location: 'Islamabad',
    jobType: 'Internship',
    workMode: 'Hybrid',
    salaryMin: 25000,
    salaryMax: 35000,
    currency: 'PKR',
    experienceYears: 0,
    education: 'Bachelor',
    skills: ['Excel', 'PowerPoint', 'Research'],
    description: 'Support the strategy team with market research and business analysis.',
    responsibilities: 'Conduct market research.\nPrepare reports.\nSupport project teams.',
    requirements: 'Analytical mindset.\nProficiency in Excel.\nGood presentation skills.',
    benefits: 'Stipend, mentorship, certificate.',
    postedDate: daysAgo(11),
    deadline: daysAgo(2),
    featured: false,
    status: 'Active',
    rating: 4.0,
    applicantsCount: 35,
  },
  {
    id: 'j21',
    title: 'Content Writer',
    companyId: 'c2',
    category: 'marketing',
    subcategory: 'Content Creator',
    location: 'Remote',
    jobType: 'Freelance',
    workMode: 'Remote',
    salaryMin: 40000,
    salaryMax: 80000,
    currency: 'PKR',
    experienceYears: 1,
    education: 'Bachelor',
    skills: ['SEO Writing', 'Blogging', 'Research'],
    description: 'Write engaging blog posts, articles, and website copy for clients.',
    responsibilities: 'Research topics.\nWrite SEO-friendly content.\nEdit and proofread.',
    requirements: 'Strong writing skills.\nSEO basics.\nPortfolio of writing samples.',
    benefits: 'Remote, flexible deadlines.',
    postedDate: daysAgo(6),
    deadline: daysAhead(8),
    featured: false,
    status: 'Active',
    rating: 4.1,
    applicantsCount: 27,
  },
  {
    id: 'j22',
    title: 'Entry-Level React Developer',
    companyId: 'c1',
    category: 'technology',
    subcategory: 'React Developer',
    location: 'Karachi',
    jobType: 'Full Time',
    workMode: 'On Site',
    salaryMin: 90000,
    salaryMax: 140000,
    currency: 'PKR',
    experienceYears: 0,
    education: 'Bachelor',
    skills: ['React', 'JavaScript', 'HTML', 'CSS'],
    description: 'Start your career as a React developer with mentorship from senior engineers.',
    responsibilities: 'Build UI components.\nFix bugs.\nLearn best practices.',
    requirements: 'Basic React knowledge.\nGood JavaScript fundamentals.\nEagerness to learn.',
    benefits: 'Mentorship, health insurance, training budget.',
    postedDate: daysAgo(3),
    deadline: daysAhead(14),
    featured: true,
    status: 'Active',
    rating: 4.2,
    applicantsCount: 42,
  },
];
